### ISSUE TITLE
nimibook: a port of mdbook to nim(ib)

### ISSUE THREAD

**Issue by pietroppeter** [beef331/website#20]
Name: nimibook

Authors: @pietroppeter, @clonkk, @hugogranstrom, @zetashift

Posting:
This month we collaboratively worked on [nimibook],
a port of [mdbook] to nim using [nimib].
Nimibook allows to create a nice looking book from nim code and markdown, making sure that nim code is running correctly and being able to incorporate code outputs in the final book.
The work started with the goal of using nimib to write [SciNim/getting-started], a guide for scientific libraries in Nim.
We are now close (not there yet) to a working version of nimibook and next month
we plan to start using it in SciNim/getting-started. Join us, we are having fun!

[mdbook]: https://rust-lang.github.io/mdBook/index.html
[nimib]: https://pietroppeter.github.io/nimib/
[SciNim/getting-started]: https://github.com/SciNim/getting-started
[nimibook]: https://pietroppeter.github.io/nimibook/

**Comment by pietroppeter** [comment]
I would ask the other authors mentioned here to review this and suggest modifications. Their inclusion in this post was preliminary discussed here: https://github.com/pietroppeter/nimibook/pull/17#issuecomment-850407108

**Comment by Clonkk** [comment]
Looks good to me

**Comment by HugoGranstrom** [comment]
Looks good to me too 😄👍

**Comment by pietroppeter** [comment]
(small edits above)

**Comment by zetashift** [comment]
Looks good to me too!

Thank you a lot for starting nimib, I really like the idea behind it :heart:
