### ISSUE TITLE
Dik

### ISSUE THREAD

**Issue by juancarlospaco** [beef331/website#22]
Name: Dik

Author: Juan Carlos

Posting:

Dik is a dictionary implemented as `{ array[char]: Option[T] }`

- [Cute pet.](https://en.wikipedia.org/wiki/Dik-dik)
- Destructors.
- Resize in-place.
- Sorted and hashed.
- Same size as Table.
- Dollar and `pretty`.
- `toSeq` and `toDik`.
- Tests for everything.
- Documentation with examples.
- Same size and speed as `Table`.
- 1 file, 300 lines, 0 dependencies.
- `newDikOfCap` for custom capacity.
- Keys are stored as `array` of `char`.
- Values are stored as `seq` of `Option[T]`.
- Can be used like `seq` or like `Table`.
- `len` for lenght and `cap` for capacity.
- Get items by `string` or `openArray[char]`.
- Get items by index or `BackwardsIndex` or `Slice[int]`.
- Iterators, including `enumerated` yields `(index, key, value)`.
- From stdlib uses only `options` for `Option[T]`, `hashes` for `hash(T)`.

![f2539200-ae72-11eb-84df-b96fde56868a](https://user-images.githubusercontent.com/1189414/120318423-38571680-c2b6-11eb-9592-85e396d7c597.jpeg)

```nim
import std/options ## For Option[T] ops.
import std/json    ## For heterogeneous values.
import dik

var myDik = {"key0": %*{"foo": 42, "bar": 3.14}, "key1": %*["baz", true]}.toDik

doAssert myDik.len == 2                        # Length
doAssert myDik.cap == 2                        # Capacity
doAssert sizeOf(myDik) == 32

doAssert myDik[1].get == %*["baz", true]       # Get by index
doAssert myDik[^1].get == %*["baz", true]      # Get by BackwardsIndex
doAssert myDik["key1"].get == %*["baz", true]  # Get by key
doAssert myDik[1..1][0].get == %*["baz", true] # Get by Slice[int]

echo myDik.pretty                              # Pretty-print
doAssert myDik.toSeq is seq[Option[JsonNode]]  # Dik to seq
doAssert "key0" in myDik                       # contains(key)
myDik.del "key1"                               # Delete an item

for (index, key, value) in myDik.enumerated:   # Iterators
  doAssert index == 0
  doAssert key == "key0"
  doAssert value.get == %*{"foo": 42, "bar": 3.14}

# Can store the lack of a value, without using "nil".
myDik["key1"] = none JsonNode
doAssert not(myDik[1].isSome)
doAssert myDik[1] == myDik["key1"]

clear myDik
doAssert myDik.len == 0
doAssert $myDik == "{:}"

```

- https://juancarlospaco.github.io/dik

**Comment by ghost** [comment]
interesting, but what's the actual difference vs tables?

**Comment by beef331** [comment]
A major benefit is it encourage him to write `doAssert sizeOf(myDik) == 32` so atleast 10 points for comedy
