### ISSUE TITLE
Harpoon

### ISSUE THREAD

**Issue by juancarlospaco** [beef331/website#25]
Name: HTTP Harpoon

Author: Juan

Posting: 

- Same API as stdlib `HttpClient`.
- 1 file, 0 dependencies, 300 lines, pure Nim.
- No Curl nor LibCurl dependencies.
- Async and sync client.
- Works with ARC and ORC. Works with `strictFuncs`.
- Uses `Uri` type for URL.
- `GET` and `POST` from JSON to JSON directly.
- `downloadFile` that takes `openArray` of URLs.
- HTTP Headers can be compile-time immutable `const`.
- Proxy support, with Auth.
- Response has `isIpv6: bool` attribute.
- Timeout support for Async and Sync.
- Option to skip parsing headers or status code or body, if you dont need them.
- HTTP Methods use `HttpMethod` enum, not strings. Status code use `HttpCode` not integers.
- Share a `Socket` with multiple clients, reuse `Socket`.
- Theres no open/close functions for the client, just call `get()` or `post()`.
- Works with Threads, Tasks, and other Async implementations.
- Uses very few symbols from stdlib, very future proof.
- `runnableExamples` with `doAssert` for everything.
- Documentation online.

### GET and POST

Examples require to import `harpoon` and `uri`.

```nim
echo getContent(parseUri"http://httpbin.org/get")
echo postContent(parseUri"http://httpbin.org/post", "data here")
```

### GET and POST from JsonNode to JsonNode

```nim
import std/json
let jsonData: JsonNode = %*{"key": "value", "other": 42}
doAssert getJson(parseUri"http://httpbin.org/get") is JsonNode
doAssert postJson(parseUri"http://httpbin.org/post", jsonData) is JsonNode
```

### Download files

```nim
downloadFile(parseUri"http://httpbin.org/image/png", "temp.png")
downloadFile([(url: parseUri"http://httpbin.org/image/png", path: "temp.png"), 
              (url: parseUri"http://httpbin.org/image/jpg", path: "temp.jpg")])
```

### HTTP Headers can be const

```nim
const header = newDefaultHeaders("body", "application/json", "application/json")
# Use std/sequtils to manipulate the header or something...
```

### Async

```nim
import std/asyncdispatch

proc example() {.async.} =
  doAssert getContent("http://httpbin.org/get") is Future[string]
  doAssert deleteContent("http://httpbin.org/delete") is Future[string]
  doAssert putContent("http://httpbin.org/put", "data here") is Future[string]
  doAssert postContent("http://httpbin.org/post", "data here") is Future[string]
  doAssert patchContent("http://httpbin.org/patch", "data here") is Future[string]
  doAssert downloadFile("http://httpbin.org/image/png", "temp.png") is Future[void]

waitFor example()
```

### PUT, DELETE, etc

```nim
echo deleteContent(parseUri"http://httpbin.org/delete")
echo putContent(parseUri"http://httpbin.org/put", "data here")
echo patchContent(parseUri"http://httpbin.org/patch", "data here")
```

- https://juancarlospaco.github.io/harpoon

**Comment by beef331** [comment]
Due to only having a single submission this will be held until more projects, just for more quantity.
