### ISSUE TITLE
Drawim

### ISSUE THREAD

**Issue by GabrielLasso** [beef331/website#29]
Name: [Drawim](https://github.com/GabrielLasso/drawim)

Author: [Gabriel Lasso](https://github.com/GabrielLasso)

Posting: 
A drawing library in Nim, inspired by p5js. Builds to native, using OpenGL, and to JavaScript, using HTML5 Canvas.

It allows you to create simulations, visualize structures, make 2D plots and even prototype 2D games with an easy and intuitive synax.

Example to draw a recursive tree:
```nim
import drawim, std/math

proc branch(len: int) =
  if (len < 1):
    return
  line(0, 0, 0, len)

  push()
  translate(0, len)
  rotate(PI / 5)
  branch(int(float(len)*0.7))
  pop()

  push()
  translate(0, len)
  rotate(-PI / 5)
  branch(int(float(len)*0.7))
  pop()

proc draw() =
  background(200)
  stroke(30, 150, 15)
  translate(int(width / 2), height)
  rotate(PI)

  branch(100)

run(600, 400, draw)
```
Result:
![Captura de tela de 2021-09-13 21-55-41](https://user-images.githubusercontent.com/12103372/133176317-e9a01577-d801-4c8d-8feb-3aef00b21f4f.png)

More examples:
- [Snake game](https://github.com/GabrielLasso/drawim/tree/master/examples/snake)
- [Orbits simulation](https://github.com/GabrielLasso/drawim/blob/master/examples/orbits.nim)
- [Sierpinski triangle](https://github.com/GabrielLasso/drawim/blob/master/examples/sierpinski.nim)
- [Ploting a function](https://github.com/GabrielLasso/drawim/blob/master/examples/xcubed.nim)
- [Game of life](https://github.com/GabrielLasso/drawim/blob/master/examples/gameoflife.nim)
- [And more](https://github.com/GabrielLasso/drawim/tree/master/examples)

**Comment by beef331** [comment]
Worth noting you don't have `jscanvas`, `opengl`, `staticGflw` pinned to a version in your nimble which can result in problems.

**Comment by GabrielLasso** [comment]
> Worth noting you don't have `jscanvas`, `opengl`, `staticGflw` pinned to a version in your nimble which can result in problems.

Thanks, I fixed the versions in the nimble file
