### ISSUE TITLE
Game: Turing Complete

### ISSUE THREAD

**Issue by Stuffe** [beef331/website#37]
Name: Your Project Name
Turing Complete

Author: Your Name or Nickname
Stuffe

Posting: Your writeup here
In this challenging puzzle game, you build a computer from scratch and program it. It is a journey through the layers of abstractions of the computer. The game begins when you are abducted by aliens who are testing your intelligence, and from here a lighthearted sci-fi plot evolves.

Steam link:
https://store.steampowered.com/app/1444480/Turing_Complete/

**Comment by ghost** [comment]
Also don't forget the link:
https://store.steampowered.com/app/1444480/Turing_Complete/
