### ISSUE TITLE
web dev blog post

### ISSUE THREAD

**Issue by ajusa** [beef331/website#38]
Name: Using Nim for Web Development in 2021

Author: ajusa

Posting: 
https://arhamjain.com/2021/11/22/nim-webdev.html
A quick (opinionated) overview of the Nim webdev ecosystem in 2021. Goes into using Nim for frontend, templating, and backend frameworks.

**Comment by beef331** [comment]
This might be more suited as a community blog post instead of on TMWN.

**Comment by ajusa** [comment]
Do you think it is high quality enough to be a guest blog post? Also it's kind of opinionated, those are the only two reasons why I wasn't sure if I should submit it.

**Comment by ghost** [comment]
Yeah I'm not exactly sure about posting it as a guest post if it's opinionated, it's fine to submit it as TMWN
