### ISSUE TITLE
MCD

### ISSUE THREAD

**Issue by EchoPouet** [beef331/website#41]
Name: [MCD](https://gitlab.com/malicious-commit-detector/mcd)

Author: [EchoPouet](https://gitlab.com/EchoPouet)

Posting:
MCD (Malicious Commit Detector) is an application to detect which commit generates malicious code detection by antivirus software.

MCD use the [Virus Total](https://www.virustotal.com) web API to detect malicious code in files. You need a API key that you can get with a free Virus Total account.
A pro account is prefered if you have lot of files to check because the free version limit the number of request.

To analyse your project commits, you must create a file to explain how build the project that you will test.

The file is a TOML format et must contains this keys:

* project_dir : path of the project source code. Absolute path or relative to this file.
* build_dir : folder where the commands must be run. Relative path to project_dir.
* build_command : a list of succesive commands to run to build your project. Relative path to project_dir.
* file_path : a list of all files to analyse. Relative path to project_dir.

To analyze the project's master branch, run the following command:
```
.\mcd.exe detectCommit -a=XXXXXXXXXX -c=c:\Users\A\mcd\tests\mcd-config.toml -b=master
Configuration file: c:\Users\A\mcd\tests\mcd-config.toml
🔍 Commit "70740ce"
🔨 Build
⏳ Wait analyze 25 sec ...
  analyze not completed, wait 25 sec ...
  analyze not completed, wait 25 sec ...
  analyze not completed, wait 25 sec ...
❌ malicious.exe
🔍 Commit "c92584b"
🔨 Build
⏳ Wait analyze 25 sec ...
  analyze not completed, wait 25 sec ...
  analyze not completed, wait 25 sec ...
  analyze not completed, wait 25 sec ...
✔️ malicious.exe
Commit "c92584b" is the last commit without generated malicous files
```

**Comment by beef331** [comment]
Given there have not been any other postings this will most likely be delayed until February.
