### ISSUE TITLE
API binding template

### ISSUE THREAD

**Issue by tandy-1000** [beef331/website#47]
Name: [API binding template](https://github.com/tandy-1000/api-binding-template/)

Author: tandy1000

Posting:
After maintaining 3 sets of REST API bindings in Nim I've amassed some useful boilerplate which the community will benefit from.

### Features:
- Out of the box support for native C / C++ and JS backend.
- Built in [jsony](https://github.com/treeform/jsony/) hooks for:
   - snake_case APIs,
   - Option types,
- Uses `fastsync` pragma from [asyncutils](https://github.com/tandy-1000/asyncutils) to enable sync / async with reduced code duplication.

This was built with help from [beef](https://github.com/beef331/) and [dylan](https://github.com/dylhack/).

**Comment by beef331** [comment]
Are you just talking about this or do you have a link to the project?

**Comment by tandy-1000** [comment]
> Are you just talking about this or do you have a link to the project?

Sorry forgot to link it hahaha
