### ISSUE TITLE
Public Analytics for Nim

### ISSUE THREAD

**Issue by pietroppeter** [beef331/website#60]
**Name:** Public Analytics for Nim

**Author:** @pietroppeter

**Posting:**

This month (October 2022) has been the first month where Nim website analytics have been available publicly
for everyone to consult, here is a snapshot of the dashboard on October 31st:

![image](https://user-images.githubusercontent.com/4997234/199054562-7c394603-304b-4b53-bf14-cae079cc9d5e.png)

Can you spot the day of nimconf? 😜

By **Public** Analytics I mean that anyone has access to the dashboard, indeed you can explore the data yourself: https://plausible.io/nim-lang.org

- can you guess what are the top three sources of traffic for the month?
- how many views did last edition of "This month with Nim" had?
- is your country in the top ten list of visitors? how many nim visitors from your city?
- more mobile or more desktop vistors? what if you filter for a specific blogpost?

The analytics in the dashboard are provided by [plausible analytics](https://plausible.io), which is an analytics service that provides simple metrics which are privacy focused, and in particular, they are **very easy to set up and to share the analytics publicly**! I have been a happy user of plausible for a while, at some point I had a subscription with space for many views and I decided that as part of my sponsorship efforts for Nim, I would be happy to commit on keep funding this analytics for some time. Plausible is open source and can be self hosted, which are nice benefits.

I see this is the beginning of a process of migrating away from Google Analytics (which is currently still used). There will be other steps along the way before being able to drop google analytics (including migrating GA data into plausible), I will keep working on this and my plan would be at some point to publish a blogpost dedicated to this activity with more explanations. If you have questions, the forum thread where this blogpost will be shared could be a good place to start a discussion.

Other references:
- PR that adds plausible to nim website: https://github.com/nim-lang/website/pull/339
- Issue that tracks next steps: https://github.com/nim-lang/website/issues/342

**Comment by beef331** [comment]
Sadly given this is the only submission this likely will not appear this month, perhaps it might be a nice blog post?

**Comment by pietroppeter** [comment]
> Sadly given this is the only submission this likely will not appear this month, perhaps it might be a nice blog post?

yeah, no problem. I will do a blogpost on the matter, but further down the road when this activity has further proceeded. I might decide to post it as a forum post or leave it here until november, time will tell. :)

**Comment by beef331** [comment]
Added to October.
