### ISSUE TITLE
pigeon

### ISSUE THREAD

**Issue by ghost** [beef331/website#61]
**Name:** pigeon

**Author:** Liam Scaife

**Posting:**

Pigeon replaces HTTP boilerplate with simple Nim procedures. When compiling to C (and friends), procedures defined within the `autoRoute` macro are automatically exposed as an API via Jester. When compiling to JS, matching procedures are created that make requests to the API. All arguments and return values are marshaled into JSON for the journey.

The result is procs you can define on the server, then call from a webapp, letting you develop them together.

Install with `nimble install pigeon`. More info and usage examples at [https://github.com/dizzyliam/pigeon](https://github.com/dizzyliam/pigeon).

**Comment by beef331** [comment]
Added to October.
