### ISSUE TITLE
nim-tilengine

### ISSUE THREAD

**Issue by exelotl** [beef331/website#62]
Name: nim-tilengine

Author: [exelotl](https://exelo.tl/)

Posting:

[nim-tilengine](https://sr.ht/~exelotl/nim-tilengine/) is a set of bindings for [Tilengine](https://www.tilengine.org/), a free, cross-platform 2D rendering engine for creating retro-style games using tilemaps, sprites and palettes. Many oldschool tricks are supported such as palette-based animation and per-scanline raster effects. Rendering is all done in software. The implementation is efficient and can run well even on a Raspberry Pi.

The Nim bindings strip away all the cruft from the C API, becoming shorter and more readable than even the official Python bindings, while keeping native performance!

Example:

<img src="https://user-images.githubusercontent.com/569607/199141355-a005e3b9-c36c-49e7-b355-fb720cc7d533.png" alt="Screenshot of a cave level from Goodboy Galaxy running in an SDL window." width="480">

```nim
import tilengine

let engine = init(320, 180, numLayers = 4, numSprites = 128, numAnimations = 128)

let map = loadTilemap("assets/map.tmx")
Layer(0).setTilemap(map)

createWindow()
while processWindow():
  drawFrame()

map.delete()
deleteWindow()
deinit()
```

**Comment by beef331** [comment]
Added to October.
