### ISSUE TITLE
🐳🗞️ news from nimib-land

### ISSUE THREAD

**Issue by pietroppeter** [beef331/website#70]
**name**: news from nimib-land

**author**: @pietroppeter, @hugogranstrom

In January we set our goals for 2023 and in February we started to deliver.
We discuss goals, progress and next steps in 🎪*Nimib Speaking Hours*,
a loosely monthly appointment open to everyone from the curious person that has never used nimib,
to the aspiring contributor.
They are announced in [nimib forum](https://github.com/pietroppeter/nimib/discussions/178), join us!

So what are the goals for 2023?

- for nimib repo we have various improvements roughly split in first and second half of the year,
see the [labels 2023H1 and 2023H2](https://github.com/pietroppeter/nimib/issues?q=is%3Aissue+label%3A2023H1%2C2023H2)
- among the big goals for the first half of the year is a move to [nimib-org](https://github.com/nimib-org),
indeed we plan next month to actually move all our nimib-related repos there, please be patient if there
are some turbulunces 
- the other big goal for the first half of the year is to finally create a general purpose Static Site Generator (SSG)
that works with nimib, currently to create a good looking website with nimib content there is only nimibook,
which is limited (on purpose, which makes it simple to pick up, and simple is good).
- for nimibook repo we have also lined up a number of improvements: https://github.com/pietroppeter/nimibook/issues?q=is%3Aissue+label%3A2023H1%2C2023H2
(basically cover most functionlaties of mdbook, including delivering a binary on install and support SUMMARY.md)
- the second half of the year is planned to be reserved for some refactorings, changing some of the internals of nimib
(to be able to deliver more fancy features) and refactoring nimibook with the upcoming SSG
- among the other goals of is to start working on [nimibex](https://github.com/nimib-org/nimibex), a repo for
extensions, extras and experiments for nimib ecosystem
- most of the planned extensions are currently blogposts in [nblog](https://github.com/pietroppeter/nblog),
which we are also working on making a proper blog

What is the current progress?
- we had [4 releases in nimib](https://github.com/pietroppeter/nimib/releases), mostly maintenance and minor stuff,
the big news is that nimib is now nim v2.0 ready!
- we had [2 releases in nimibook](https://github.com/pietroppeter/nimibook/releases), in particular 0.3 release
finally catches up the documentation on a lot of work done last year (including work from new contributor @beef331).
Ah, nimibook is also v2.0 ready!

So what are next steps?
- complete the [ongoing work on making nblog a proper blog](https://github.com/pietroppeter/nblog/pull/16), while a the same time progressing
on one of the key ingredients of the future SSG: a nimib document will be rendered to json and the json later converted to html
- start working on nimibex
- move res to nimib-org

For more details you can look at the meeting notes from [January](https://github.com/pietroppeter/nimib/discussions/162#discussioncomment-4811966) and [February](https://github.com/pietroppeter/nimib/discussions/178#discussioncomment-5139070) speaking hours,
you can ask stuff in nimib discussion forum (hopefully soon taht will become nimib-org discussion forum),
or elsewhere.

*disclaimer*: note that all these plans on doing stuff come with a very loose open source commitment:
we work on these projects on our free time, we do it because we enjoy it, we will not get stressed
if we do not manage to complete our plans, whatever happens in life means we might need to redirect our energy elsewhere.

**Comment by pietroppeter** [comment]
note for @beef331: please wait for @hugogranstrom to review this. Also if you need help to create the final post in nim website let me know.

@hugogranstrom: the content is there for you to review. I think it could use some improvements in styling (make it a bit more joyful). I also paste below the content of raw markdown, in case you want to edit:

```md
**name**: news from nimib-land

**author**: @pietroppeter, @hugogranstrom

In January we set our goals for 2023 and in February we started to deliver.
We discuss goals, progress and next steps in 🎪*Nimib Speaking Hours*,
a loosely monthly appointment open to everyone from the curious person that has never used nimib,
to the aspiring contributor.
They are announced in [nimib forum](https://github.com/pietroppeter/nimib/discussions/178), join us!

So what are the goals for 2023?

- for nimib repo we have various improvements roughly split in first and second half of the year,
see the [labels 2023H1 and 2023H2](https://github.com/pietroppeter/nimib/issues?q=is%3Aissue+label%3A2023H1%2C2023H2)
- among the big goals for the first half of the year is a move to [nimib-org](https://github.com/nimib-org),
indeed we plan next month to actually move all our nimib-related repos there, please be patient if there
are some turbulunces 
- the other big goal for the first half of the year is to finally create a general purpose Static Site Generator (SSG)
that works with nimib, currently to create a good looking website with nimib content there is only nimibook,
which is limited (on purpose, which makes it simple to pick up, and simple is good).
- for nimibook repo we have also lined up a number of improvements: https://github.com/pietroppeter/nimibook/issues?q=is%3Aissue+label%3A2023H1%2C2023H2
(basically cover most functionlaties of mdbook, including delivering a binary on install and support SUMMARY.md)
- the second half of the year is planned to be reserved for some refactorings, changing some of the internals of nimib
(to be able to deliver more fancy features) and refactoring nimibook with the upcoming SSG
- among the other goals of is to start working on [nimibex](https://github.com/nimib-org/nimibex), a repo for
extensions, extras and experiments for nimib ecosystem
- most of the planned extensions are currently blogposts in [nblog](https://github.com/pietroppeter/nblog),
which we are also working on making a proper blog

What is the current progress?
- we had [4 releases in nimib](https://github.com/pietroppeter/nimib/releases), mostly maintenance and minor stuff,
the big news is that nimib is now nim v2.0 ready!
- we had [2 releases in nimibook](https://github.com/pietroppeter/nimibook/releases), in particular 0.3 release
finally catches up the documentation on a lot of work done last year (including work from new contributor @beef331).
Ah, nimibook is also v2.0 ready!

So what are next steps?
- complete the [ongoing work on making nblog a proper blog](https://github.com/pietroppeter/nblog/pull/16), while a the same time progressing
on one of the key ingredients of the future SSG: a nimib document will be rendered to json and the json later converted to html
- start working on nimibex
- move res to nimib-org

For more details you can look at the meeting notes from
[January](https://github.com/pietroppeter/nimib/discussions/162#discussioncomment-4811966) and
[February](https://github.com/pietroppeter/nimib/discussions/178#discussioncomment-5139070) speaking hours,
you can ask stuff in nimib discussion forum (hopefully soon taht will become nimib-org discussion forum),
or elsewhere.

*disclaimer*: note that all these plans on doing stuff come with a very loose open source commitment:
we work on these projects on our free time, we do it because we enjoy it, we will not get stressed
if we do not manage to complete our plans, whatever happens in life means we might need to redirect our energy elsewhere.
```

**Comment by HugoGranstrom** [comment]
@pietroppeter Looks good to me :D I've fixed a few typos and restructured some sentences:

```md
**name**: news from nimib-land

**author**: @pietroppeter, @hugogranstrom

In January we set our goals for 2023 and in February we started delivering progress on them.

We discuss goals, progress and next steps in 🎪*Nimib Speaking Hours*,
a loosely monthly appointment open to everyone from the curious person that has never used nimib,
to the aspiring contributor.
They are announced in [nimib forum](https://github.com/pietroppeter/nimib/discussions/178), join us!

So what are the goals for 2023?

- for nimib itself we have various improvements roughly split into the first and second half of the year,
see the [labels 2023H1 and 2023H2](https://github.com/pietroppeter/nimib/issues?q=is%3Aissue+label%3A2023H1%2C2023H2)
- among the big goals for the first half of the year is a move to [nimib-org](https://github.com/nimib-org).
Indeed we plan next month to actually move all our nimib-related repos there, please be patient if there
are some turbulunces 
- the other big goal for the first half of the year is to finally create a general purpose Static Site Generator (SSG)
that works with nimib. Currently to create a good looking website with nimib content there is only nimibook,
which is limited (on purpose, which makes it simple to pick up, and simple is good).
- for nimibook we have also lined up a number of improvements: https://github.com/pietroppeter/nimibook/issues?q=is%3Aissue+label%3A2023H1%2C2023H2
(basically covers most functionalities of mdbook, including delivering a binary on install and supporting SUMMARY.md)
- the second half of the year is planned to be reserved for some refactorings, changing some of the internals of nimib
(to be able to deliver more fancy features) and refactoring nimibook with the upcoming SSG
- among the other goals of is to start working on [nimibex](https://github.com/nimib-org/nimibex), a repo for
extensions, extras and experiments for the nimib ecosystem
- most of the planned extensions are currently blogposts in [nblog](https://github.com/pietroppeter/nblog),
which we are also working on turning into a proper blog

What is the current progress?
- we had [4 releases in nimib](https://github.com/pietroppeter/nimib/releases), mostly maintenance and minor stuff,
the big news is that nimib is now nim v2.0 ready!
- we had [2 releases in nimibook](https://github.com/pietroppeter/nimibook/releases), in particular 0.3 release
finally catches up the documentation on a lot of work done last year (including work from new contributor @beef331).
Ah, nimibook is also v2.0 ready!

So what are next steps?
- complete the [ongoing work on making nblog a proper blog](https://github.com/pietroppeter/nblog/pull/16), while a the same time progressing
on one of the key ingredients of the future SSG: a nimib document will be rendered to json and the json later converted to html
- start working on nimibex
- move repos to nimib-org

For more details you can look at the meeting notes from
[January](https://github.com/pietroppeter/nimib/discussions/162#discussioncomment-4811966) and
[February](https://github.com/pietroppeter/nimib/discussions/178#discussioncomment-5139070) speaking hours,
you can ask stuff in nimib discussion forum (hopefully soon that will become nimib-org discussion forum),
or elsewhere.

*disclaimer*: note that all these plans on doing stuff come with a very loose open source commitment:
we work on these projects on our free time, we do it because we enjoy it, we will not get stressed
if we do not manage to complete our plans, whatever happens in life means we might need to redirect our energy elsewhere.
```
