### ISSUE TITLE
Karkas

### ISSUE THREAD

**Issue by moigagoo** [beef331/website#83]
Name: Karkas

Author: moigagoo

Posting:

**Karkas** is a library that makes creating web sites with Karax a bit more pleasant. It offers a bunch of styles to build layouts and some syntactic sugar to save you typing.

Karkas allows you to create complex layouts by combining basic primitives. It also offers a clean syntax for style combination, which lets you write clear code and be obvious about your intentions as a programmer.

For example, you can write something like this: `tdiv(style = hStack() <- box(2) <- {border: "solid"})`. Which means there's a vertical stack which is in turn a box of size 2 inside another container, with a solid border.

Find the official tutorial at https://karkas.nim.town.

Repo: https://github.com/moigagoo/karkas

**Comment by pietroppeter** [comment]
typo https://karkas.nom.town/ -> https://karkas.nim.town/

**Comment by beef331** [comment]
Sorry @pietroppeter you did not hear‽ With 2.0 it's now Nom! :stuck_out_tongue:

**Comment by pietroppeter** [comment]
wait I get distracted for a moment and you changed the name of the language?! 😆

**Comment by moigagoo** [comment]
> typo https://karkas.nom.town/ -> https://karkas.nim.town/

Oops, my bad :-)
